spring.application.name=PRATIK-DAIRY-USER

spring.datasource.driver-class-name = org.mariadb.jdbc.Driver
spring.datasource.url = jdbc:mariadb://localhost:3306/pratik_dairy_user?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username = root
spring.datasource.password = 123456
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

server.port = 8081

user.url = http://localhost:8081/users

management.endpoints.web.exposure.include=*

springdoc.swagger-ui.path = /user-docs

# JWT Configuration
# SECRET: production mein ise env variable se set karo
#   Windows:  set JWT_SECRET=<your-64-char-random-string>
#   Linux/Mac: export JWT_SECRET=<your-64-char-random-string>
# EXPIRATION: 3600000 = 1 hour (milliseconds)


# ${JWT_SECRET:PratikDairyLocalDevSecretKey_ChangeThisInProduction_MinLength32}
jwt.secret="pratikdairypratikdairypratikdairypratikdairy"
# ${JWT_EXPIRATION_MS:3600000}
jwt.expiration=3600000

#Eureka configuration
eureka.instance.prefer-ip-address = true
eureka.client.fetch-registry = true
eureka.client.register-with-eureka = true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/